FROM node:alpine AS build

WORKDIR /app

COPY frontend/package.json /app/frontend/package.json
COPY backend/package.json /app/backend/package.json

WORKDIR /app/frontend
RUN npm install --production
WORKDIR /app/backend
RUN npm install --production

WORKDIR /app
COPY . .

# Build the frontend application
WORKDIR /app/frontend
RUN npm run build

WORKDIR /app/backend
RUN npm run build

FROM node:alpine

WORKDIR /app

COPY --from=build /app/backend/dist /app
COPY --from=build /app/backend/node_modules /app/node_modules

EXPOSE 3000

CMD ["node", "backend/server.js"]
