#!/bin/bash
FROM node:lts-alpine AS builder
LABEL authors="oscar"

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build-dev

EXPOSE 3000
CMD ["npm", "run", "start-backend"]
