#!/bin/bash
FROM node:lts-alpine AS build-stage
LABEL authors="oscar"

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build-prod

FROM node:lts-alpine AS production-stage

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY --from=build-stage /app/dist/ dist/
COPY --from=build-stage /app/backend.ts ./

EXPOSE 3000
CMD ["node", "backend.ts"]
