name: Development Preview

on:
  push:
    branches:
      - 'dev'

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build and push to GitHub Pages
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'redstarmy'
          reponame: 'geeek_server'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
